// Mocks generated by Mockito 5.0.16 from annotations
// in flutterando_playlist_test/test/unit_tests/task_bloc_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:flutterando_playlist_test/models/task.dart' as _i5;
import 'package:flutterando_playlist_test/repositories/task_repository.dart'
    as _i3;
import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeClient_0 extends _i1.Fake implements _i2.Client {}

/// A class which mocks [TaskRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskRepository extends _i1.Mock implements _i3.TaskRepository {
  MockTaskRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client => (super.noSuchMethod(Invocation.getter(#client),
      returnValue: _FakeClient_0()) as _i2.Client);
  @override
  _i4.Future<List<_i5.Task>> getTasks() =>
      (super.noSuchMethod(Invocation.method(#getTasks, []),
              returnValue: Future<List<_i5.Task>>.value(<_i5.Task>[]))
          as _i4.Future<List<_i5.Task>>);
  @override
  String toString() => super.toString();
}
